[mobilenet]
lazy = true
git-tree-sha1 = "4141d9dbac70f9cfd172c0b14b0f8dcc01466cc1"

    [[mobilenet.download]]
    url = "https://github.com/UW-PHARM/bitstream-hackathon/raw/gh-pages/assets/mobilenet.tar.gz"
    sha256 = "db5d49d4a039d3aa8e982f6434f460e5c2b2d09fb99a58ff4b825cd9be5699e7"
